CONSUMER_KEY: <your consumer key>
CONSUMER_SECRET: <your consumer secret>
API_MWURI: <url of the api, for Wikimedia Commons https://commons.wikimedia.org/w/api.php>
OAUTH_MWURI: <url of OAuth endplace, for Wikimedia Commons https://commons.wikimedia.org/w/index.php>
SECRET_KEY: <something long and secret>
